# Site settings
title: tanjiquan Blog   #你博客的标题
SEOTitle: 谭继全的博客 | tanjiquan Blog #显示在浏览器上搜索的时候显示的标题
header-img: img/home-bg.jpg #显示在首页的背景图片
email: tan_jiquan@163.com
description: "世界那么美，走出去看看。"   #网站介绍
keyword: "谭继全, 谭继全, 谭, 继全, tan, jiquan, tanjiquan的博客, tanjiquan Blog, 博客, 个人网站, 互联网, Web, Java, 大数据"
url: "https://tanjiquan.github.io"             # 博客地址
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     jiquantan
zhihu_username:     tanjiquan
github_username:    tanjiquan
#twitter_username:   tanjiquan
#facebook_username:  tanjiquan
jianshu_username:   4f0239f60572
#linkedin_username:  tan.ji.quan.jessy



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings（这里是shortname 不是username），这里不用 Disqus，Disqus 需要翻墙才能看
# disqus_username: https-tanjiquan-github-io

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e2b87a4864fbae0d02ef                            #生成的clientID
  clientSecret: 21b503f21f41f53a3b71877e006c3e887e0f904a    #生成的clientSecret
  repo: tanjiquan.github.io    #仓库名称
  owner: tanjiquan    #github用户名
  admin: tanjiquan
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: tanjiquan.github.io


# Sidebar settings
sidebar: true                          # 是否开启侧边栏.
sidebar-about-description: "Trust the process<br>相信过程"
sidebar-avatar: /img/avatar-tan-ny.jpg      # 你的个人头像


# 在首页可以看到的特色标签，当你的文章出现相同标签（默认相同的标签数量大于1），才会自动生成。
#将其修改为featured-condition-size: 0, 这样只有一个标签时也会出现在首页了。
#相反，当你博客比较多，标签也很多时，这时你就需要改回 1 甚至是 2 了。
# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "me",
        href: "https://tanjiquan.github.io/"
    },{
        title: "repo",
        href: "https://github.com/tanjiquan?tab=repositories"
    }
]
